name: UpdateConfigs

on:
  workflow_dispatch:  # اجازه اجرای دستی
  ##  schedule:
  ##  - cron: '0 9,21 * * *'  # هر روز در ساعت 9 صبح و 9 شب (UTC)

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run the index.ts file
      - name: Run index.ts
        run: bun index.ts
