name: UpdateConfigs

on:
  workflow_dispatch:  # اجازه اجرای دستی
  ##  schedule:
  ##  - cron: '0 9,21 * * *'  # هر روز در ساعت 9 صبح و 9 شب (UTC)

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install dependencies
        run: bun install

      # Run the index.ts file
      - name: Run index.ts
        run: bun index.ts

      # Add URL to BadChannels.txt
      #- name: Add URL to UpdateConfigs.txt
      # run: |
      #  echo "https://github.com/mohamadfg-dev/telegram-v2ray-configs-collector/blob/main/category/" >> category/*

      # Commit changes
      - name: Commit changes to UpdateConfigs.txt
        run: |
          git config --local user.name "Robot-1"
          git config --local user.email "Robot@example.com"
          git add category/*
          git commit -m "UpdateConfigs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
