name: Update Time

on:
  workflow_dispatch:  # اجازه اجرای دستی

jobs:
  update-time:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update time.txt
        run: echo "$(date)" > time.txt
        
      - name: Commit and push changes
        run: |
          git config --local user.email "mohamadfg.dev@gmail.com"
          git config --local user.name "mohamadfg-dev"
          git add time.txt
          git commit -m "Update time.txt with current time" || echo "No changes to commit"
          git push
