name: UpdateConfigs

on:
  workflow_dispatch: # اجازه اجرای دستی
 # schedule:
 #   - cron: "0 */2 * * *" # هر دو ساعت یک بار

jobs:
  my-job:
    name: UpdateConfigs
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      # Run the index.ts file
      - name: Run index.ts
        run: bun index.ts
        
      # Commit changes
      - name: Commit Changes To UpdateConfigs
        run: |
          git config --local user.name "Robot-1"
          git config --local user.email "Robot@example.com"
          git add category/*
          git add BadChannels.txt
          git commit -m "UpdateConfigs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
